// status.js
const SUBMITTED = 'SUBMITTED';
const IN_PROGRESS = 'IN_PROGRESS';
const REJECTED = 'REJECTED';
const SCHEDULED_FOR_PAYMENT = 'SCHEDULED_FOR_PAYMENT';
const PAID = 'PAID';

module.exports = {
  SUBMITTED,
  IN_PROGRESS,
  REJECTED,
  SCHEDULED_FOR_PAYMENT,
  PAID,

  VALID_STATUSES: [
    SUBMITTED,
    IN_PROGRESS,
    REJECTED,
    SCHEDULED_FOR_PAYMENT,
    PAID,
  ],

  ALLOWED_STATUS_TRANSITIONS: {
    SUBMITTED: [IN_PROGRESS, REJECTED],
    IN_PROGRESS: [SCHEDULED_FOR_PAYMENT, REJECTED],
    SCHEDULED_FOR_PAYMENT: [PAID],
    PAID: [],
    REJECTED: [SUBMITTED],
  },
};