// status.js
const SUBMITTED: string = 'SUBMITTED';
const IN_PROGRESS: string = 'IN_PROGRESS';
const REJECTED: string = 'REJECTED';
const SCHEDULED_FOR_PAYMENT: string = 'SCHEDULED_FOR_PAYMENT';
const PAID: string = 'PAID';

const VALID_STATUSES: string[] = [
  SUBMITTED,
  IN_PROGRESS,
  REJECTED,
  SCHEDULED_FOR_PAYMENT,
  PAID,
];

const ALLOWED_STATUS_TRANSITIONS: { [key: string]: string[] } = {
  SUBMITTED: [IN_PROGRESS, REJECTED],
  IN_PROGRESS: [SCHEDULED_FOR_PAYMENT, REJECTED],
  SCHEDULED_FOR_PAYMENT: [PAID],
  PAID: [],
  REJECTED: [SUBMITTED],
};

module.exports = {
  SUBMITTED,
  IN_PROGRESS,
  REJECTED,
  SCHEDULED_FOR_PAYMENT,
  PAID,

  VALID_STATUSES,

  ALLOWED_STATUS_TRANSITIONS
};